### PR TITLE
Develop_李嘉欣

### PR DESCRIPTION
**Pull request by Leega1020**
http://54.248.30.27:3000/api/attractions?page=3
http://54.248.30.27:3000/api/attractions?page=0&keyword=北
http://54.248.30.27:3000/api/attractions?page=0&keyword=士林
http://54.248.30.27:3000/api/attraction/10
http://54.248.30.27:3000/api/mrts

### CODE REVIEW

**Comment by cwpeng** [comment]
We should query data from MySQL database in our web server, not from JSON file.

Leave comment here after you fixed it.

**Comment by Leega1020** [comment]
fix query data from MySQL database in my web server.

**Review by cwpeng — COMMENTED** [review]
We never get all data when server started. Database usually stored large dataset which that your server can not load to memory at once. Just get necessory data from database when we have to handle request.

Re-request review after you fixed this issue.

**Comment by Leega1020** [comment]
Fix get all data from database

**Comment by cwpeng** [comment]
Re-request review from top right corner in this page so that I can review for you again.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
