### PR TITLE
Develop_week2_李嘉欣

### PR DESCRIPTION
**Pull request by Leega1020**
http://54.248.30.27:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. When we click on arrows, we should implement **scrolling effect** on MRT list in any size of devices without scrollbar appearing.
2. Attraction text breaks into 2 lines and exceed the block in about 600px width devices.
3. Search icon disappers in the middle size of devices.

未命名-4

**Comment by Leega1020** [comment]
Fixed the problems

**Review by cwpeng — CHANGES_REQUESTED** [review]
I do not see **scrolling effect**. It means we will get an animation to scroll text smoothly, you can review meet recording to find it.

**Comment by Leega1020** [comment]
Added scrolling effect.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by cwpeng** [comment]
You should merge pull request after review approval next time.

**Pull request closed without merging**
